.TH WHENEVERIZE 1 2014-08-30 "Ruby Gem" "whenever"

.SH NAME
wheneverize - utility for creating initial config/schedule.rb file

.SH SYNOPSIS
\fBwheneverize\fR [\fIPATH\fR]

.SH DESCRIPTION
\fBwheneverize\fR(1) will create initial config/schedule.rb file.

.SH BUGS
If you've found a genuine bug or issue, please use the Issues section on github: \fIhttp://github.com/javan/whenever/issues\fR.

.SH AUTHORS
Javan Makhmali <javan@javan.us>

.SH SEE ALSO
\fBwhenever\fR(1)
\fIhttps://github.com/javan/whenever\fR
